app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from cars.views import CarsListView, NewCarCreateView, CarDetailView, CarUpdateView, CarDeleteView
from accounts.views import register_view, login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('cars/', CarsListView.as_view(), name='cars_list'),
    path('new_car/', NewCarCreateView.as_view(), name='new_car'),
    path('car/<int:pk>/', CarDetailView.as_view(), name='car_detail'),
    path('car/<int:pk>/update', CarUpdateView.as_view(), name='car_update'),
    path('car/<int:pk>/delete', CarDeleteView.as_view(), name='car_delete')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

cars/models.py
from django.db import models
from django.contrib.auth.models import User


class Brand(models.Model):
  id = models.AutoField(primary_key=True)
  name = models.CharField(max_length=100)

  def __str__(self):
    return self.name


class Car(models.Model):
  id = models.AutoField(primary_key=True)
  model = models.CharField(max_length=100)
  brand = models.ForeignKey(Brand, on_delete=models.PROTECT, related_name='cars_brand')
  factory_year = models.IntegerField(null=True)
  model_year = models.IntegerField(null=True)
  plate = models.CharField(max_length=8, null=True, blank=True)
  price = models.FloatField(blank=True, null=True)
  photo = models.ImageField(upload_to='cars/', blank=True, null=True)
  bio = models.TextField(blank=True, null=True)

  owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='cars')

  def __str__(self):
    return self.model
  
class CarInventory(models.Model):
  cars_count = models.IntegerField()
  cars_price = models.FloatField()
  created_at = models.DateTimeField(auto_now_add=True)

  class Meta:
    ordering = ['-created_at']
  
  def __str__(self):
    return f'{self.cars_count} - {self.cars_price}'

cars/forms.py
from django import forms
from cars.models import Car
  
class CarModelForm(forms.ModelForm):
  class Meta:
    model = Car
    exclude = ['owner']
    fields = '__all__'
    widgets = {
        'photo': forms.ClearableFileInput(attrs={'class': 'file-input'}),
      }

  def clean_price(self):
    price = self.cleaned_data.get('price')
    if price < 20000:
      raise forms.ValidationError('Não é permitido o cadastro de carros menores de R$20.000')
    return price
  
  def clean_factory_year(self):
    factory_year = self.cleaned_data.get('factory_year')
    if factory_year < 1975:
      raise forms.ValidationError('Não é permitido o cadastro de carros abaixo de 1975')
    return factory_year
  
  def clean_model_year(self):
    model_year = self.cleaned_data.get('model_year')
    if model_year < 1975:
      raise forms.ValidationError('Não é permitido o cadastro de carros abaixo de 1975')
    return model_year

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import  authenticate,login, logout

def register_view(request):
  if request.method == 'POST':
    user_form = UserCreationForm(request.POST)
    if user_form.is_valid():
      user_form.save()
      return redirect('login')
  else:
    user_form = UserCreationForm()
  return render(request, 'register.html', {'user_form': user_form})


def login_view(request):
  if request.method == 'POST':
    login_form = AuthenticationForm(request, data=request.POST)
    if login_form.is_valid():
      username = request.POST['username']
      password = request.POST['password']
      user = authenticate(request, username=username, password=password)
      if user is not None:
        login(request, user)
        return redirect('cars_list')
  else:
    login_form = AuthenticationForm()
  return render(request, 'login.html', {'login_form': login_form})

def logout_view(request):
    logout(request)
    return redirect('cars_list')

cars/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from cars.models import Car
from cars.forms import CarModelForm
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView


class CarsListView(ListView):
  model = Car
  template_name = 'cars.html'
  context_object_name = 'cars'

  def get_queryset(self):
    cars = super().get_queryset().order_by('model')
    search = self.request.GET.get('search')
    if search:
      cars = cars.filter(model__icontains=search)
    return cars
  
class NewCarCreateView(LoginRequiredMixin, CreateView):
  login_url = 'login'
  redirect_field_name = 'next'

  model = Car
  form_class = CarModelForm
  template_name = 'new_car.html'
  success_url = '/cars/'

  def form_valid(self, form):
    form.instance.owner = self.request.user
    return super().form_valid(form)

class CarDetailView(DetailView):
  model = Car
  template_name = 'car_detail.html'
  context_object_name = 'car'

class CarUpdateView(LoginRequiredMixin, UpdateView):
  login_url = 'login'
  redirect_field_name = 'next'

  model = Car
  form_class = CarModelForm
  template_name = 'car_update.html'
  success_url = '/cars/'

  def get_queryset(self):
    if self.request.user.is_superuser:
      return Car.objects.all()
    return Car.objects.filter(owner=self.request.user)


class CarDeleteView(LoginRequiredMixin, DeleteView):
  login_url = 'login'
  redirect_field_name = 'next'

  model = Car
  template_name = 'car_delete.html'
  success_url = '/cars/'
  
  def get_queryset(self):
    if self.request.user.is_superuser:
      return Car.objects.all()
    return Car.objects.filter(owner=self.request.user)

accounts/templates/login.html
{% extends "base.html" %}

{% block content %}
<style>
    form {
    max-width: 480px;
    margin: 60px auto;     
    padding: 40px;
    background: #005977;
    border-radius: 12px;
    box-shadow: 0 6px 20px rgba(0,0,0,0.3);
    @media(max-width: 768px){
        width: 320px;
    }
    }

    .form-group input {
    width: 100%;
    box-sizing: border-box;
    padding: 12px;
    border-radius: 6px;
    }

    h3 {
        color: #fff;
        font-weight: 600;
        text-align: center;
        font-size: 36px;
        margin-bottom: 25px;
    }

    .form-group {
        margin-bottom: 20px;
        text-align: left;
        color: #fff;
    }

    label {
        display: block;
        margin-bottom: 6px;
        font-size: 14px;
        font-weight: 600;
        color: #ddd;
    }

    input {
        width: 100%;
        padding: 12px;
        border-radius: 6px;
        border: 1px solid #ccc;
        background: #f9f9f9;
        font-size: 16px;
        transition: all 0.2s ease-in-out;
    }

    input:focus {
        outline: none;
        border-color: #0096c7;
        box-shadow: 0 0 6px rgba(0,150,199,0.6);
    }

    .btn {
        display: block;
        width: 100%;
        padding: 12px;
        margin-top: 20px;
        text-transform: uppercase;
        font-weight: bold;
        border: none;
        border-radius: 6px;
        background: #0096c7;
        color: white;
        cursor: pointer;
        font-size: 16px;
        transition: background 0.3s ease-in-out;
    }

    .btn:hover {
        background: #0077a2;
    }

    .errorlist {
        color: #ff4b4b;
        font-size: 14px;
        margin: 8px 0 0;
        list-style: none;
        padding-left: 0;
        font-weight: normal;
    }
    .search-form{
        display: none;
    }
    </style>

    <form method="post">
        {% csrf_token %}
        <h3>Login</h3>
        {% if login_form.non_field_errors %}
        <div class="errorlist">
            {% for error in login_form.non_field_errors %}
                <p>{{ error }}</p>
            {% endfor %}
        </div>
    {% endif %}
        <div class="form-group">
                {{ login_form.username.errors }}
            <label>Usuário: </label>
                {{ login_form.username }}
        </div>
        <div class="form-group">
                {{ login_form.password.errors }}
            <label>Senha: </label>
                {{ login_form.password }}
        </div>

        <input type="submit" value="Login" class="btn btn-primary">
    </form>

{% endblock %}

accounts/templates/register.html
{% extends "base.html" %}

{% block content %}
    <style>
    form {
    max-width: 480px;
    margin: 60px auto;     
    padding: 40px;
    background: #005977;
    border-radius: 12px;
    box-shadow: 0 6px 20px rgba(0,0,0,0.3);
    @media(max-width: 768px){
        width: 320px;
    }
    }

    .form-group input {
    width: 100%;
    box-sizing: border-box;
    padding: 12px;
    border-radius: 6px;
    }

    h3 {
        color: #fff;
        font-weight: 600;
        text-align: center;
        font-size: 36px;
        margin-bottom: 25px;
    }

    .form-group {
        margin-bottom: 20px;
        text-align: left;
        color: #fff;
    }

    label {
        display: block;
        margin-bottom: 6px;
        font-size: 14px;
        font-weight: 600;
        color: #ddd;
    }

    input {
        width: 100%;
        padding: 12px;
        border-radius: 6px;
        border: 1px solid #ccc;
        background: #f9f9f9;
        font-size: 16px;
        transition: all 0.2s ease-in-out;
    }

    input:focus {
        outline: none;
        border-color: #0096c7;
        box-shadow: 0 0 6px rgba(0,150,199,0.6);
    }

    .btn {
        display: block;
        width: 100%;
        padding: 12px;
        margin-top: 20px;
        text-transform: uppercase;
        font-weight: bold;
        border: none;
        border-radius: 6px;
        background: #0096c7;
        color: white;
        cursor: pointer;
        font-size: 16px;
        transition: background 0.3s ease-in-out;
    }

    .btn:hover {
        background: #0077a2;
    }

    .errorlist {
        color: #ff4b4b;
        font-size: 14px;
        margin: 8px 0 0;
        list-style: none;
        padding-left: 0;
        font-weight: normal;
    }
    .search-form{
        display: none;
    }
    </style>

    <form method="post">
    {% csrf_token %}
    <h3>Cadastro</h3>

    <div class="form-group">
        <label for="id_username">Usuário:</label>
        {{ user_form.username }}
        {{ user_form.username.errors }}
    </div>

    <div class="form-group">
        <label for="id_password1">Senha:</label>
        {{ user_form.password1 }}
        {{ user_form.password1.errors }}
    </div>

    <div class="form-group">
        <label for="id_password2">Confirmação de senha:</label>
        {{ user_form.password2 }}
        {{ user_form.password2.errors }}
    </div>

    <button type="submit" class="btn">Cadastrar</button>
    </form>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %}</title>
  <style>
    body {
        font-family: 'Open Sans', sans-serif;
        background-color: #f7f7f7;
        color: #333;
        margin: 0;
        padding: 0;
    }

    header {
        background-color: #0096c7;
        color: #fff;
        text-align: center;
        padding: 12px;

        @media(max-width: 768px){
          padding: 6px;
        }
    }

    footer {
        background-color: #ccc;
        color: #333;
        padding: 20px;
        text-align: center;
    }

    nav {
        background-color: #0096c7;
        color: #fff;
        height: 50px;
        display: flex;
        justify-content: space-between;
        align-items: center;
    }

    nav ul {
        list-style: none;
        margin: 0;
        padding: 0;
        display: flex;
    }

    nav ul li {
        margin: 0 10px;
    }

    nav ul li a {
        color: #fff;
        text-decoration: none;
        font-size: 16px;
        padding: 15px;
        transition: all 0.3s ease;
    }

    nav ul li a:hover {
        background-color: #32bbe8;
        border-radius: 4px;
    }

    nav ul li.active a {
        background-color: #666;
    }

    nav ul li.active a:hover {
        background-color: #999;
    }

    .username, .btn-register{
      position: absolute;
      right: 80px;

      @media(max-width: 768px){
      right: 60px;
      }
    }

    .username{
      text-transform: capitalize;
    }

    .btn-logout, .btn-login{
      position: absolute;
      right: 2px;
    }

    .search-box {
      display: flex;
      align-items: center;
      background: #fff;
      border-radius: 6px;
      overflow: hidden;
      box-shadow: 0 2px 6px rgba(0, 0, 0, 0.2);
    }

    .search-box input[type="text"] {
      border: none;
      padding: 10px 15px;
      font-size: 16px;
      outline: none;
      width: 230px;
      @media(max-width: 768px){
        width: 130px;
        padding: 6px 8px;
        font-size: 12px;
      }
    }

    button{
      border-radius: 0px;
    }


  .search-box button {
    background: #005470;
    border: none;
    color: #fff;
    padding: 10px 20px;
    font-size: 16px;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: background-color 0.3s ease-in-out;
  }

  .search-box button:hover {
    background: #01465e;
  }
  </style>
</head>
<body>
  <header>
    <nav>
      <ul>
        <form method="GET" action="{% url 'cars_list' %}" class="search-form">
          <div class="search-box">
          <input type="text" name="search" placeholder="Buscar carro...">
          <button type="submit">
          <svg xmlns="http://www.w3.org/2000/svg" 
            width="20" height="20" 
            fill="currentColor" 
            viewBox="0 0 16 16">
          <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001l3.85 
          3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85zm-5.242 
          1.656a5 5 0 1 1 0-10 5 5 0 0 1 0 10z"/>
        </svg>
        </button>
        </div>
        </form>
        {% if user.is_authenticated %}
          <li class="username">Olá, {{ user.username }}</li>
          <li><a href="{% url 'new_car' %}">Cadastrar Carro</a></li>
        {% endif %}
        {% if not user.is_authenticated %}
          <li class="btn-login"><a href="{% url 'login' %}">Login</a></li>
          <li class="btn-register"><a href="{% url 'register' %}">Cadastre-se</a></li>
        {% endif %}
        {% if user.is_authenticated %}
          <li class="btn-logout"><a href="{% url 'logout' %}">Sair</a></li>
        {% endif %}
        
        <li><a href="{% url 'cars_list' %}">Carros</a></li>
      </ul>
    </nav>
  </header>

  <main>
    {% block content %}
    {% endblock %}
  </main>

  <footer>
    <p>&copy; 2025 Bonardi Multimarcas</p>
  </footer>
</body>
</html>

cars/templates/car_delete.html
{% extends "base.html" %}

{% block content %}
  <style>
    .buttons-container {
      display: flex;
      justify-content: center;
      margin-top: 20px;
      margin-bottom: 20px;
    }

    .btn {
      display: inline-block;
      background-color: #0096c7;
      color: #fff;
      border: none;
      padding: 10px 20px;
      font-size: 16px;
      border-radius: 4px;
      cursor: pointer;
      transition: background-color 0.3s ease-in-out;
      margin: 0 10px;
    }

    .btn:hover {
      background-color: #108eb8;
    }

    .btn-danger {
      background-color: #d9534f;
      text-decoration: none !important;
    }

    .btn-danger:hover {
      background-color: #d2221c;
    }

    .error-message {
      color: #d9534f;
      font-size: 14px;
      margin-top: 5px;
    }

    a {
      text-decoration: none !important;
    }

    p, .card-title{
      text-align: center;
    }

    .search-form{
      display: none;
    }
  </style>
  <div class="card">
    <div class="card-header">
      <h1 class="card-title">Deletar Carro</h1>
    </div>
    <div class="card-body">
      <p>Tem certeza que deseja deletar o carro <strong>{{ object.brand }} {{ object.model }}</strong>?</p>
      <form method="post">
        {% csrf_token %}
        <div class="buttons-container">
          <button type="submit" class="btn btn-danger">Deletar Carro</button>
          <a href="{% url 'car_update' pk=object.pk %}" class="btn btn-secondary">Cancelar</a>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

cars/templates/car_detail.html
{% extends "base.html" %}

{% block content %}
  <style>
    .car-card {
      background-color: #e3e1e1;
      box-shadow: 0 2px 6px rgba(0, 0, 0, 0.2);
      border-radius: 10px;
      overflow: hidden;
      text-align: center;
      transition: all 0.3s ease;
      max-width: 500px;
      margin: 20px auto 0;
      margin-bottom: 20px;
      @media(max-width: 768px){
        width: 90%;
      }
    }

    .car-card:hover {
      cursor: pointer;
      box-shadow: 0 4px 10px rgba(0, 0, 0, 0.4);
      transform: translateY(-2px);
    }

    .car-card img {
      width: 100%;
      height: 300px;
      object-fit: cover;
      @media(max-width: 768px){
        height: 200px;
      }
    }

    .car-card h2 {
      font-size: 1.5rem;
      margin: 10px;
    }

    .car-card p {
      font-size: 1rem;
      margin-bottom: 10px;
    }

    .buttons-container {
      display: flex;
      justify-content: center;
      margin-top: 20px;
      margin-bottom: 20px;
    }

    .btn {
      display: inline-block;
      background-color: #0096c7;
      color: #fff;
      border: none;
      padding: 10px 20px;
      font-size: 16px;
      border-radius: 4px;
      cursor: pointer;
      transition: background-color 0.3s ease-in-out;
      margin: 0 10px;
    }

    .btn:hover {
      background-color: #108eb8;
    }

    .btn-danger {
      background-color: #d9534f;
      text-decoration: none !important;
    }

    .btn-danger:hover {
      background-color: #d2221c;
    }

    .error-message {
      color: #d9534f;
      font-size: 14px;
      margin-top: 5px;
    }

    a {
      text-decoration: none !important;
    }
    .search-form{
      display: none;
    }

    .bio{
      display: block;
      padding: 0 8px;
      font-weight: 600;
    }

  </style>
  <div class="car-card">
      {% if car.photo %}
        <img src="{{ car.photo.url }}" alt="{{ car.model }} - {{ car.brand }}">
      {% else %}
        <img src="https://www.umabaloes.com/content/interfaces/cms/themes/skyline/images/noimg.jpg">
      {% endif %}
      <h2>{{ car.brand }} {{ car.model }}</h2>
      <p><strong>Ano de fabricação:</strong> {{ car.factory_year }}</p>
      <p><strong>Ano do modelo:</strong> {{ car.model_year }}</p>
      <p><strong>Placa:</strong> {{ car.plate }}</p>
      <p><strong>Preço:</strong> R${{ car.price }}</p>
      {% if car.bio %}
        <p class="bio"><strong>Bio:</strong> {{ car.bio }}</p>
      {% endif %}
      {% if user.is_authenticated and car.owner == user %}
        <p><strong>Registrado por: </strong>Você</p>
      {% else %}
        <p><strong>Registrado por:</strong> {{ car.owner }}</p>
      {% endif %}
  </div>
  {% if user.is_authenticated and car.owner == user or user.is_superuser %}
    <div class="buttons-container">
    <a href="{% url 'car_update' pk=car.pk %}" class="btn btn-primary">Editar</a>
    <a href="{% url 'car_delete' pk=car.pk %}" class="btn btn-danger">Deletar</a>
    </div>
  {% endif %}
{% endblock %}

cars/templates/car_update.html
{% extends "base.html" %}

{% block content %}

  <style>
    form {
      max-width: 400px;
      margin: 34px auto;
      padding: 20px;
      background-color: #f5f5f5;
      border-radius: 10px;
      box-shadow: 0 2px 6px rgba(0, 0, 0, 0.2);
    }
    form input {
      @media(max-width: 768px){
        width: 250px;
      }
    }

    form h1 {
      font-size: 2rem;
      margin-bottom: 20px;
      text-align: center;
    }

    table {
      margin: 0 auto;
      border-collapse: collapse;
      width: 100%;
      max-width: 600px;
      
    }

    th, td {
      padding: 4px;
      text-align: left;
      border-bottom: 1px solid #ddd;
    }

    th {
      background-color: #f2f2f2;
    }

    input[type="text"], input[type="number"], select, textarea {
      padding: 8px;
      font-size: 14px;
      border: 2px solid #ddd;
      border-radius: 4px;
      width: 100%;
      max-width: 300px;
      margin-bottom: 8px;
      transition: border-bottom-color 0.3s ease-in-out;
      @media(max-width: 768px){
        width: 200px;
      }
    }

    input[type="text"]:focus, input[type="number"]:focus, select:focus, textarea:focus {
      outline: none;
      border-bottom-color: #0096c7;
    }

    .btn {
      background-color: #0096c7;
      color: #fff;
      border: none;
      padding: 10px 20px;
      font-size: 16px;
      border-radius: 4px;
      cursor: pointer;
      transition: background-color 0.3s ease-in-out;
    }

    .buttons-container {
      display: flex;
      justify-content: center;
      margin-top: 20px;
      margin-bottom: 20px;
    }

    .btn {
      display: inline-block;
      background-color: #0096c7;
      color: #fff;
      border: none;
      padding: 10px 20px;
      font-size: 16px;
      border-radius: 4px;
      cursor: pointer;
      transition: background-color 0.3s ease-in-out;
      margin: 0 10px;
    }

    .btn:hover {
      background-color: #108eb8;
    }

    .btn-danger {
      background-color: #d9534f;
      text-decoration: none !important;
    }

    .btn-danger:hover {
      background-color: #d2221c;
    }

    .error-message {
      color: #d9534f;
      font-size: 14px;
      margin-top: 5px;
    }

    a {
      text-decoration: none !important;
    }

    .search-form{
      display: none;
    }

  </style>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h1>Editar Carro</h1>
    <table>
      {{ form.as_table }}
    </table>
    <div>
      <div class="buttons-container">
        <input type="submit" value="Salvar Alterações" class="btn btn-primary">
        <a href="{% url 'cars_list' %}" class="btn btn-secondary">Cancelar</a>
      </div>
    </div>
  </form>
{% endblock %}

cars/templates/new_car.html
{% extends "base.html" %}

{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Novo carro</title>
</head>

<style>
    form {
    max-width: 480px;
    margin: 60px auto;     
    padding: 40px;
    background: #005977;
    border-radius: 12px;
    box-shadow: 0 6px 20px rgba(0,0,0,0.3);
    @media(max-width: 768px){
        width: 300px;
      }
    }

    .form-group input {
    width: 100%;
    box-sizing: border-box;
    padding: 12px;
    border-radius: 6px;
    }

    h3 {
        color: #fff;
        font-weight: 600;
        text-align: center;
        font-size: 36px;
        margin-bottom: 25px;
        @media(max-width: 768px){
        font-size: 24px;
      }
    }

    .form-group {
        margin-bottom: 20px;
        text-align: left;
        color: #fff;
    }

    label {
        display: block;
        margin-bottom: 6px;
        font-size: 14px;
        font-weight: 600;
        color: #ddd;
    }

    input {
        width: 100%;
        padding: 12px;
        border-radius: 6px;
        border: 1px solid #ccc;
        background: #f9f9f9;
        font-size: 16px;
        transition: all 0.2s ease-in-out;
        @media(max-width: 768px){
        padding: 8px;
        font-size: 12px;
      }
    }

    input:focus {
        outline: none;
        border-color: #0096c7;
        box-shadow: 0 0 6px rgba(0,150,199,0.6);
    }

    .btn {
        display: block;
        width: 100%;
        padding: 12px;
        margin-top: 20px;
        text-transform: uppercase;
        font-weight: bold;
        border: none;
        border-radius: 6px;
        background: #0096c7;
        color: white;
        cursor: pointer;
        font-size: 16px;
        transition: background 0.3s ease-in-out;
    }

    .btn:hover {
        background: #0077a2;
    }

    .errorlist {
        color: #ff4b4b;
        font-size: 14px;
        margin: 8px 0 0;
        list-style: none;
        padding-left: 0;
        font-weight: normal;
    }
    .search-form{
        display: none;
    }

        textarea{
          width: 100%;
          border-radius: 5px;
          resize: none;

          &:focus{
            outline: none;
          }
        }

        select{
          width: 100%;
          text-align: center;
          padding: 12px;
          border-radius: 6px;
          border: none;

          &:focus{
            outline: none;
          }
        }

  .file-input {
    display: none;
  }

  .file-label {
    display: inline-block;
    padding: 10px 20px;
    background: #0096c7;
    color: white;
    border-radius: 8px;
    font-weight: 600;
    cursor: pointer;
    transition: background-color 0.2s ease;
  }

  .file-label:hover {
    background: #0077a2;
  }

  .file-name {
    margin-left: 10px;
    font-size: 0.9rem;
    color: #62d0f8;
  }
    </style>

<body>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h3>Cadastrar Carro</h3>
    <div class="form-group">
      <label>Modelo: </label>
      {{ form.model }}
      
    </div>
    <div class="form-group fab">
      <label>Fabricante: </label>
        {{ form.brand }}
    </div>
    <div class="form-group">
      <label>Ano de fabrica: </label>
      {{ form.factory_year }}
      {{ form.factory_year.errors }}
    </div>
    <div class="form-group">
      <label>Ano de modelo: </label>
      {{ form.model_year }}
      {{ form.model_year.errors }}
    </div>
    <div class="form-group">
      <label>Placa: </label>
      {{ form.plate }}
    </div>
    <div class="form-group">
      <label>Preço: </label>
      {{ form.price.errors }}
      {{ form.price }}
    </div>
    <div class="form-group">
      <label>Bio: </label>
      {{ form.bio }}
    </div>
    <div class="form-group">
    <label for="id_photo">Foto:</label>
    <label for="id_photo" class="file-label">Escolher imagem</label>
    {{ form.photo }}
    <span id="fileName" class="file-name">Nenhum arquivo selecionado</span>
    </div>
    <input type="submit" value="Cadastrar" class="btn btn-primary">
  </form>
</body>
<script>
  const input = document.getElementById('id_photo');
  const nameSpan = document.getElementById('fileName');
  input.addEventListener('change', () => {
    nameSpan.textContent = input.files[0]?.name || 'Nenhum arquivo selecionado';
  });
</script>
</html>

{% endblock %}